services:
  _defaults:
    public: true

  pdir.mobileDe.listener.hooks:
    class: Pdir\MobileDeBundle\EventListener\HooksListener

  pdir.mobileDe.listener.dataContainer:
    class: Pdir\MobileDeBundle\EventListener\DataContainerListener
