<?php

/*
 * mobile.de bundle for Contao Open Source CMS
 *
 * Copyright (c) 2021 pdir / digital agentur // pdir GmbH
 *
 * @package    mobilede-bundle
 * @link       https://pdir.de/mobilede.html
 * @license    proprietary / pdir license - All-rights-reserved - commercial extension
 * @author     Mathias Arzberger <develop@pdir.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Pdir\MobileDeBundle\EventListener\DataContainerListener;

$strTable = 'tl_vehicle';

$GLOBALS['TL_DCA'][$strTable] = [
    'config' => [
        'dataContainer' => 'Table',
        'switchToEdit' => true,
        'enableVersioning' => true,
        'sql' => [
            'keys' => [
                'id' => 'primary',
            ],
        ],
    ],
    'list' => [
        'sorting' => [
            'mode' => 1,
            'fields' => ['vehicle_model_description'],
            'headerFields' => ['vehicle_model_description', 'vehicle_make', 'vehicle_class', 'vehicle_category', 'type', 'account'],
            'flag' => 1,
            'panelLayout' => 'debug;filter;sort,search,limit',
        ],
        'label' => [
            'fields' => ['vehicle_model_description', 'vehicle_make', 'vehicle_class', 'vehicle_category', 'type', 'account'],
            // 'format' => '%s %s - %s [<span style="font-weight: bold;">%s</span>]',
            'showColumns' => true,
        ],
        'global_operations' => [
            'all' => [
                'label' => &$GLOBALS['TL_LANG']['MSC']['all'],
                'href' => 'act=select',
                'class' => 'header_edit_all',
                'attributes' => 'onclick="Backend.getScrollOffset()" accesskey="e"',
            ],
            'toggleNodes' => [
                'href' => '&amp;ptg=all',
                'class' => 'header_toggle',
                'showOnSelect' => true
            ],
            'toolbar' => [
                'button_callback' => [DataContainerListener::class, 'renderToolbar'],
                'class' => 'header_toolbar'
            ],
        ],
        'operations' => [
            'edit' => [
                'label' => &$GLOBALS['TL_LANG'][$strTable]['edit'],
                'href' => 'act=edit',
                'icon' => 'edit.gif',
            ],
            'copy' => [
                'label' => &$GLOBALS['TL_LANG'][$strTable]['copy'],
                'href' => 'act=copy',
                'icon' => 'copy.gif',
            ],
            'delete' => [
                'label' => &$GLOBALS['TL_LANG'][$strTable]['delete'],
                'href' => 'act=delete',
                'icon' => 'delete.gif',
                'attributes' => 'onclick="if(!confirm(\''.isset($GLOBALS['TL_LANG']['MSC']['deleteConfirm'])?? null.'\'))return false;Backend.getScrollOffset()"',
            ],
            'toggle' => [
                'label' => &$GLOBALS['TL_LANG']['tl_content']['toggle'],
                'icon' => 'visible.svg',
                'attributes' => 'onclick="Backend.getScrollOffset();return AjaxRequest.toggleVisibility(this,%s)"',
                'button_callback' => ['Pdir\MobileDeBundle\Dca\Ad', 'toggleIcon'],
            ],
            'show' => [
                'label' => &$GLOBALS['TL_LANG'][$strTable]['show'],
                'href' => 'act=show',
                'icon' => 'show.gif',
            ],
        ],
    ],
    'palettes' => [
        '__selector__' => ['vehicle_class'],
        'default' => '{title_legend},name,alias,type,account,vehicle_id,published;'.
            '{vehicle_legend},vehicle_class,vehicle_category,vehicle_make,vehicle_model,vehicle_model_description,vehicle_free_text,'.
                'features,vehicle_damage,images;'.
            '{price_legend},dealer_price_amount,consumer_price_amount,pseudo_price,price_vat_rate,price_currency,price_vat_rating,'.
                'price_rating,price_included_delivery_costs;'.
            '{specifics_legend},specifics_exterior_color,specifics_manufacturer_color_name,specifics_metallic,specifics_mileage,'.
                'specifics_exhaust_inspection,specifics_general_inspection,specifics_delivery_date,specifics_delivery_period,'.
                'specifics_door_count,specifics_first_registration,specifics_emission_class,specifics_emission_sticker,'.
                'specifics_fuel,specifics_power,specifics_hsn,specifics_tsn,specifics_schwacke_code,specifics_gearbox,'.
                'specifics_climatisation,specifics_licensed_weight,specifics_axles,specifics_load_capacity,specifics_num_seats,'.
                'specifics_operating_hours,specifics_installation_height,specifics_lifting_capacity,specifics_lifting_height,'.
                'specifics_construction_year,specifics_construction_date,specifics_cubic_capacity,specifics_driving_mode,'.
                'specifics_driving_cab,specifics_condition,specifics_usage_type,specifics_wheel_formula,specifics_number_of_bunks,'.
                'specifics_hydraulic_installation,specifics_europallet_storage_spaces,specifics_dimension_length,specifics_dimension_width,'.
                'specifics_dimension_height,specifics_shipping_volume,specifics_loading_space_length,specifics_loading_space_width,'.
                'specifics_identification_number,specifics_interior_color,specifics_interior_type,specifics_airbag,'.
                'specifics_number_of_previous_owners,specifics_countryVersion,specifics_videoUrl,specifics_parking_assistants,'.
                'specifics_speed_control,specifics_radio,specifics_daytime_running_lamps,specifics_sliding_door_type,'.
                'specifics_headlight_type,specifics_bending_lights_type,specifics_breakdown_service,specifics_battery,'.
                'specifics_trailer_coupling_type,specifics_trim_line,specifics_model_range,specifics_first_models_production_date,'.
                'specifics_battery_capacity;'.
            '{emission_fuel_consumption_legend},emission_fuel_consumption_envkv_compliant,emission_fuel_consumption_energy_efficiency_class,'.
                'emission_fuel_consumption_co2_emission,emission_fuel_consumption_inner,emission_fuel_consumption_outer,'.
                'emission_fuel_consumption_combined,emission_fuel_consumption_petrol_type,emission_fuel_consumption_combined_power_consumption;'.
            '{wltp_values_legend},wltp_consumption_fuel_combined,wltp_co2_emission_combined,wltp_consumption_power_combined,'.
                'wltp_electric_range,wltp_consumption_fuel_combined_weighted,wltp_consumption_power_combined_weighted,'.
                'wltp_co2_emission_combined_weighted;',
    ],
    'subpalettes' => [],
    'fields' => [
        'id' => [
            'sql' => 'int(10) unsigned NOT NULL auto_increment',
        ],
        'tstamp' => [
            'sql' => "int(10) unsigned NOT NULL default '0'",
        ],
        'published' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['published'],
            'exclude' => true,
            'filter' => true,
            'inputType' => 'checkbox',
            'eval' => ['doNotCopy' => true, 'tl_class' => 'w50'],
            'sql' => "char(1) NOT NULL default ''",
        ],
        'name' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['name'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'vehicle_id' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_id'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'alias' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['alias'],
            'exclude' => true,
            'search' => true,
            'inputType' => 'text',
            'eval' => ['rgxp' => 'alias', 'unique' => true, 'maxlength' => 128, 'tl_class' => 'w50'],
            'save_callback' => ['Pdir\MobileDeBundle\Dca\Ad', 'generateAlias'],
            'sql' => "varchar(128) COLLATE utf8_bin NOT NULL default ''",
        ],
        'dealer_price_amount' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['dealer_price_amount'],
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NULL",
        ],
        'consumer_price_amount' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['consumer_price_amount'],
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NULL",
        ],
        'pseudo_price' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['pseudo_price'],
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => 'float(10,2) NULL',
        ],
        'price_included_delivery_costs' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['price_included_delivery_costs'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'checkbox',
            'eval' => ['mandatory' => false, 'tl_class' => 'clr'],
            'sql' => "char(1) NOT NULL default ''",
        ],
        'price_vatable' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['price_vatable'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'checkbox',
            'eval' => ['mandatory' => false, 'tl_class' => 'clr'],
            'sql' => "char(1) NOT NULL default ''",
        ],
        'price_vat_rate' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['price_vat_rate'],
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'price_vat_rating' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['price_vat_rating'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['price_vat_rating']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'price_currency' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['price_currency'],
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'price_rating' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['price_rating'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['price_rating']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['type']['options'],
            'eval' => [
                'includeBlankOption' => false,
                'tl_class' => 'w50',
                'readonly' => true,
            ],
            'sql' => "varchar(4) NOT NULL default 'man'",
        ],
        'account' => [
            'inputType' => 'select',
            'sorting' => true,
            'foreignKey' => 'tl_vehicle_account.description',
            'search' => true,
            'eval' => [
                'tl_class' => 'w50',
                'includeBlankOption' => true
            ],
            'options_callback' => [DataContainerListener::class, 'getVehicleVehicleAccountOptions'],
            'sql' => "int(10) unsigned NOT NULL default '0'",
        ],
        'creation_date' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['creation_date'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => "varchar(30) NOT NULL default ''",
        ],
        'modification_date' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['modification_date'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => "varchar(30) NOT NULL default ''",
        ],
        'vehicle_class' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_class'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_class']['options'],
            'eval' => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50', 'submitOnChange' => true, 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'vehicle_category' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_category'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_category']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'options_callback' => ['Pdir\MobileDeBundle\Dca\Ad', 'categoryOptionsCallback'],
            'sql' => 'text NULL',
        ],
        'vehicle_make' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_make'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'vehicle_model' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_model'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'vehicle_model_description' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_model_description'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'tl_class' => 'clr'],
            'sql' => 'text NULL',
        ],
        'vehicle_free_text' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_free_text'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'tl_class' => 'clr', 'rte' => 'tinyMCE'],
            'sql' => 'text NULL',
        ],
        'vehicle_damage' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_damage'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['vehicle_damage']['options'],
            'eval' => ['mandatory' => false, 'tl_class' => 'w50', 'multiple' => true, 'chosen' => true],
            'sql' => 'text NULL',
        ],
        'specifics_exterior_color' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_exterior_color'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_exterior_color']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_metallic' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_metallic'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'checkbox',
            'eval' => ['mandatory' => false, 'tl_class' => 'clr'],
            'sql' => "char(1) NOT NULL default ''",
        ],
        'specifics_manufacturer_color_name' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_manufacturer_color_name'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_mileage' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_mileage'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_exhaust_inspection' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_exhaust_inspection'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50 wizard', 'rgxp' => 'date', 'datepicker' => true],
            'sql' => 'text NULL',
        ],
        'specifics_general_inspection' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_general_inspection'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50 wizard', 'rgxp' => 'date', 'datepicker' => true],
            'sql' => 'text NULL',
        ],
        'specifics_delivery_date' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_delivery_date'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50 wizard', 'rgxp' => 'date', 'datepicker' => true],
            'sql' => 'text NULL',
        ],
        'specifics_delivery_period' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_delivery_period'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_door_count' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_door_count'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_door_count']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_first_registration' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_first_registration'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50 wizard', 'rgxp' => 'date', 'datepicker' => true],
            'sql' => 'text NULL',
        ],
        'specifics_emission_class' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_emission_class'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_emission_class']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_emission_sticker' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_emission_sticker'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_emission_sticker']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_fuel' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_fuel'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_fuel']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_power' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_power'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_hsn' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_hsn'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 4, 'tl_class' => 'w50'],
            'sql' => "varchar(4) NOT NULL default ''",
        ],
        'specifics_tsn' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_tsn'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 8, 'tl_class' => 'w50'],
            'sql' => "varchar(8) NOT NULL default ''",
        ],
        'specifics_schwacke_code' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_schwacke_code'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_gearbox' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_gearbox'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_gearbox']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_climatisation' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_climatisation'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_climatisation']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_licensed_weight' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_licensed_weight'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_axles' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_axles'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_load_capacity' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_load_capacity'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_num_seats' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_num_seats'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => "varchar(2) NOT NULL default ''",
        ],
        'specifics_operating_hours' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_operating_hours'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_installation_height' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_installation_height'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_lifting_capacity' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_lifting_capacity'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_lifting_height' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_lifting_height'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_construction_year' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_construction_year'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_construction_date' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_construction_date'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50 wizard', 'rgxp' => 'date', 'datepicker' => true],
            'sql' => 'text NULL',
        ],
        'specifics_cubic_capacity' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_cubic_capacity'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_driving_mode' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_driving_mode'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_driving_mode']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_driving_cab' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_driving_cab'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_driving_cab']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_condition' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_condition'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_condition']['options'],
            'eval' => ['maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_usage_type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_usage_type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_usage_type']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_wheel_formula' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_wheel_formula'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_wheel_formula']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_number_of_bunks' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_number_of_bunks'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_hydraulic_installation' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_hydraulic_installation'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_hydraulic_installation']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_europallet_storage_spaces' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_europallet_storage_spaces'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_dimension_length' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_dimension_length'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_dimension_width' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_dimension_width'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_dimension_height' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_dimension_height'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_shipping_volume' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_shipping_volume'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_loading_space_length' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_loading_space_length'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_loading_space_width' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_loading_space_width'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_identification_number' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_identification_number'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_interior_color' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_interior_color'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_interior_color']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_interior_type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_interior_type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_interior_type']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_airbag' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_airbag'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_airbag']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_number_of_previous_owners' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_number_of_previous_owners'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => "varchar(2) NULL default ''",
        ],
        'specifics_countryVersion' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_countryVersion'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_countryVersion']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_videoUrl' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_videoUrl'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_parking_assistants' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_parking_assistants'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_parking_assistants']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_speed_control' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_speed_control'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_speed_control']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_radio' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_radio'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_radio']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_daytime_running_lamps' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_daytime_running_lamps'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_daytime_running_lamps']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_sliding_door_type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_sliding_door_type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_sliding_door_type']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_headlight_type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_headlight_type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_headlight_type']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_bending_lights_type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_bending_lights_type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_bending_lights_type']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_breakdown_service' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_breakdown_service'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_breakdown_service']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_battery' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_battery'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_battery']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_trailer_coupling_type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_trailer_coupling_type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['specifics_trailer_coupling_type']['options'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'specifics_trim_line' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_trim_line'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_model_range' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_model_range'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'specifics_first_models_production_date' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_first_models_production_date'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50 wizard', 'rgxp' => 'date', 'datepicker' => true],
            'sql' => 'text NULL',
        ],
        'specifics_battery_capacity' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['specifics_battery_capacity'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_envkv_compliant' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_envkv_compliant'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'checkbox',
            'eval' => ['mandatory' => false, 'tl_class' => 'clr'],
            'sql' => "char(1) NOT NULL default ''",
        ],
        'emission_fuel_consumption_energy_efficiency_class' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_energy_efficiency_class'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => ['A+', 'A', 'B', 'C', 'D', 'E', 'F', 'G'],
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50', 'includeBlankOption' => true],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_co2_emission' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_co2_emission'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_inner' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_inner'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_outer' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_outer'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_combined' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_combined'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_petrol_type' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_petrol_type'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_combined_power_consumption' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_combined_power_consumption'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'emission_fuel_consumption_unit' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['emission_fuel_consumption_unit'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => [
                'mandatory' => false,
                'maxlength' => 255,
                'tl_class' => 'w50',
            ],
            'sql' => 'text NULL',
        ],
        'images' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['images'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'fileTree',
            'eval' => [
                'mandatory' => false,
                'tl_class' => 'clr',
                'multiple' => true,
                'fieldType' => 'checkbox',
                'files' => true,
                'orderField' => 'orderSRC',
            ],
            'sql' => 'blob NULL',
        ],
        'api_images' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['api_images'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'text',
            'eval' => ['mandatory' => false, 'tl_class' => 'w50'],
            'sql' => 'text NULL',
        ],
        'orderSRC' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['orderSRC'],
            'sql' => 'blob NULL',
        ],
        'features' => [
            'label' => &$GLOBALS['TL_LANG'][$strTable]['features'],
            'exclude' => true,
            'search' => true,
            'sorting' => true,
            'flag' => 1,
            'inputType' => 'select',
            'options' => &$GLOBALS['TL_LANG'][$strTable]['features']['options'],
            'eval' => ['maxlength' => 255, 'tl_class' => 'clr', 'includeBlankOption' => true, 'multiple' => true, 'chosen' => true],
            'options_callback' => ['Pdir\MobileDeBundle\Dca\Ad', 'featuresOptionsCallback'],
            'sql' => 'text NULL',
        ],
        // wltp-values
        'wltp_consumption_fuel_combined' => [
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NOT NULL default '0'",
        ],
        'wltp_co2_emission_combined' => [
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NOT NULL default '0'",
        ],
        'wltp_consumption_power_combined' => [
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NULL",
        ],
        'wltp_electric_range' => [
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "int(10) unsigned NOT NULL default '0'",
        ],
        'wltp_consumption_fuel_combined_weighted' => [
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NOT NULL default '0'",
        ],
        'wltp_consumption_power_combined_weighted' => [
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NOT NULL default '0'",
        ],
        'wltp_co2_emission_combined_weighted' => [
            'exclude' => true,
            'inputType' => 'text',
            'eval' => ['maxlength' => 13, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql' => "float(10,2) NOT NULL default '0'",
        ],
    ],
];
